### ISSUE TITLE
{"name":"AzureAD: OIDC Passport Strategy","hostname":"webapp-virtual-machine","pid":2202,"level":40,"msg":"Production environments should always validate the issuer.","time":"2020-02-01T15:23:20.190Z","v":0

### ISSUE THREAD

**Issue by ErikHoeven** [microsoftgraph/msgraph-training-nodeexpressapp#25]
I encouter the following error when running npm start
`{"name":"AzureAD: OIDC Passport Strategy","hostname":"webapp-virtual-machine","pid":2202,"level":40,"msg":"Production environments should always validate the issuer.","time":"2020-02-01T15:23:20.190Z","v":0}`

**Comment by jasonjoh** [comment]
Right. That's a warning from the Azure passport plugin because the sample does not do issuer validation. Since this is a dev environment, that's OK, but you should validate the issuer in production. You can see Azure's validation doc here: https://docs.microsoft.com/azure/active-directory/develop/access-tokens#validating-tokens

It should not hurt functionality of the sample
