### ISSUE TITLE
invalid_request after logging into the app

### ISSUE THREAD

**Issue by yhrchan** [microsoftgraph/msgraph-training-nodeexpressapp#32]
I am new to the Graph API and I've just tried pulling and running the code as per the tutorial. I've also configured the app registration accordingly on Azure AD admin center and filled out the app id and secret in the .env file. However, after logging in, it redirects me back to the home "/" page and the UI shows an "invalid_request" in a red error box. There wasn't any console.log messages and don't see much in Fiddler.

**Comment by jasonjoh** [comment]
A common cause of `invalid_request` during auth is a problem with the redirect URI. Double-check that the URI specified in `OAUTH_REDIRECT_URI` in your .env file matches up with the redirect URI you configured on your app registration exactly.

**Comment by MrJohnLocke** [comment]
I am also getting this same issue, and my reply URI matches in both the env file and in my app's authentication page in Azure.

http://localhost:3000/auth/callback

**Comment by jasonjoh** [comment]
Thanks @MrJohnLocke. How did you get the code? Did you clone this repo, download from our [quick start page](https://developer.microsoft.com/graph/quick-start), or follow the [tutorial](https://docs.microsoft.com/graph/tutorials/node)? I'm asking so I know which avenue to investigate further :).

**Comment by MrJohnLocke** [comment]
I used the Quick Start page.  It created the app in AAD, gave me the graph-tutorial folder (in a zip file).  Made sure the graph API permissions were added in the app registration.  Then I just opened the folder in VSCode, ran npm install, then npm start.  The app started just fine.  I tried to log in with my credentials, including MFA, and then it returned me to the home/index page with the error.  In VSCode, it even says that it returned me to /auth/callback after the sign-in process.

**Comment by jasonjoh** [comment]
Thanks for that. Let me check it out and post back.

**Comment by jasonjoh** [comment]
Ok I just pulled the quick start and tried to reproduce it, unsuccessfully. I want to see if maybe it's a specific combo of account types, MFA, etc.

- When you are prompted to sign in to get an app ID and secret in the quick start tool, did you use a work/school account, or a personal Microsoft account (like outlook.com, etc.)?
- When you login to the app, which type of account do you use?
- There should be a file named `version` in the root of the zip file you downloaded, can you tell me the version number in that file?
- You mentioned adding graph API permissions in the app registration - you shouldn't have to add anything. Do you remember exactly what you changed (if anything)?
- What version of node.js are you using, as reported by `node --version`?

**Comment by MrJohnLocke** [comment]
1) I have tried with two different accounts, getting the same result with each.  One of them is an onmicrosoft.com account, and the other is a Microsoft work account.  The Microsoft work account does not use MFA.  The onmicrosoft.com account does use MFA.

2) version of the zip was 1.2

3) User.Read was the only API permission after the app was added to my AAD.  I was able to add the other required perms without issue though. (Calendars.Read, offline_access, openid, profile)

4) 12.16.1

**Comment by jasonjoh** [comment]
Thanks. 1.2 is the latest version. There is no need to set those other perms on the app registration: the app requests them dynamically. However, that should not break anything. Just to be sure, I added it to my app registration and I'm still working fine :). I'm also using Node 12.16.1.

I enabled require MFA on one of my onmicrosoft.com test accounts and I don't reproduce the error. So there's some disconnect here. I'd like to see if we can get more info on your particular error. The sample uses passport.js to do the initial sign-in, with the setting to report errors in a flash message, which is what you're seeing with the red box. Passport.js seems to only show the error code, but there's usually a message that goes along with it. Let's see if we can dump the rest of that error. Can you add a `console.log(JSON.stringify(req.body));` into your `callback` in auth.js? It would look like this:

```
router.post('/callback',
  function(req, res, next) {
    console.log(JSON.stringify(req.body));
    passport.authenticate('azuread-openidconnect',
      {
        response: res,
        failureRedirect: '/',
        failureFlash: true,
        successRedirect: '/'
      }
    )(req,res,next);
  }
);
```

Let me know what that outputs.

**Comment by MrJohnLocke** [comment]
With your code, we do have some more info!  And a fix!

Here's the output: AADSTS50194: Application (My Node.js App) is not configured as a multi-tenant application. Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint or configure the application to be multi-tenant.

So in my AAD registration, I did change the supported account types from multi-tenant to single, because I only wanted accounts from my AD to have sign-in capabilities.  So it looks like this is what broke the sign-in process, because when I change back to the multi-tenant, it works just fine.

The fix for anyone wanting to only use a single tenant is to replace the "common" endpoint of OAUTH_AUTHORITY (.env file) to your tenant ID.  So it should look something like:

OAUTH_AUTHORITY=https://login.microsoftonline.com/<your-tenant-ID-here>/

Thank you for the help on this.

**Comment by jasonjoh** [comment]
Glad you figured it out :). The sample uses common just because it reduces the steps to get this working, so yep, the app registration has to be configured as multi-tenant, unless you make the code change you suggested.

@yhrchan do either of the suggestions fix your issue?

- Make sure redirect URI is correct in app registration
- Make sure app is configured as multi-tenant, or make the code change @MrJohnLocke describes above.

**Comment by yhrchan** [comment]
Hi @jasonjoh and @MrJohnLocke 

Thanks for your help. The sample created from https://developer.microsoft.com/en-us/graph/quick-start works fine without errors while the one from this repo is where I am having problems with. It turns out what @MrJohnLocke described resolved the issue to put in a tenant id in the OAUTH_AUTHORITY parameter as the one I created myself is targeted as a single-tenant.

Thank you!
