### ISSUE TITLE
How to initiate oAuth without passport

### ISSUE THREAD

**Issue by muhammadfaizan** [microsoftgraph/msgraph-training-nodeexpressapp#41]
I am looking for a way to implement oAuth of Azure without using passport. Can you please guide me regarding documentation

**Comment by jasonjoh** [comment]
@muhammadfaizan we're not set up to provide general support in GitHub issues on this sample. Since this is outside the scope of this particular sample, the best I can point you at is https://github.com/AzureAD/microsoft-authentication-library-for-js (the Microsoft auth library, which has an alpha for Node support), and https://docs.microsoft.com/azure/active-directory/develop/v2-oauth2-auth-code-flow for the protocol details.
